version: 0.2

phases:
  build:
    commands:
      - ./gradlew test

reports:
  TestReports:
    files:
      - '**/*'
    base-directory: 'build/test-results'

artifacts:
  files:
    - '**/*'
  base-directory: 'build'